---
name: SOW
about: A business request associated with a given milestone. It contains a list of Epics required to deliver.
title: "[adds/updates/removes] [what] to [where]"
assignees: awentzel
---

## Executive Summary
<!-- A summary description of the challenge or opportunity. -->

## Impact
<!-- A value statement of impact this project or task would have for the stakeholder/s -->

## Project Details
<!-- Project description and details of work to be performed -->

