

```[tasklist]
## Business Requirements
- [ ] conducts user (subject matter expert) interviews
- [ ] creates user actions/workflows
- [ ] creates user stories
```

## Project Lifecycle
<!-- Provide detailed requirements with links to resources for all activities involved in delivering this request to the stakeholders -->
<!-- consider what action or workflows are required for the stakeholder to efficiently and quickly achieve their objectives -->
<!-- consider responsive/adaptive UI, themes/branding, cross-platform / devices -->

```[tasklist]
## Discovery Tasks
- [ ] conduct competitive analysis
- [ ] conduct data analysis
- [ ] conduct user (subject matter expert) feedback interviews
```

```[tasklist]
## Definition Tasks
- [ ] create brainstorm/storyboard
- [ ] create user stories
- [ ] create information architecture
- [ ] create sketches/wireframes
- [ ] mobile vs desktop considerations
- [ ] internal feasibility review
```

```[tasklist]
## Design Tasks
- [ ] creates lo-fi design
- [ ] creates prototype in figma
- [ ] validates lo-fi with feature team
- [ ] validates MLE lo-fi UX with customer
- [ ] creates hi-fi design
- [ ] validates hi-fi with feature team
- [ ] presents hi-fi MLE to customer
```

```[tasklist]
## Development Tasks
- [ ] scopes MLE work
- [ ] create project plan
- [ ] review with leadership
```

```[tasklist]
## Delivery Tasks
- [ ] create release email
- [ ] create newsletter content
- [ ] create communication plan / schedule
```

## Contact Details
<!-- Contact information for the stakeholder -->
Name:
Email:
Phone:
Delivery Date (if applicable):
Support Ticket Reference (if applicable):

## Resource Links
- System Requirements Specification (SysRS): 
- Design: 
- Engineering:
